using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace VeradeAddin.Services
{
    /// <summary>One part the add-in generated: where it was saved and how to rebuild it.</summary>
    public sealed class PartRegistryEntry
    {
        /// <summary>Full path of the .SLDPRT on disk (the registry key, compared case-insensitively).</summary>
        public string Path { get; set; }

        /// <summary>Catalog kind: "shaft" or "bolt". Informational; the wizard mode travels in <see cref="Message"/>.</summary>
        public string Kind { get; set; }

        /// <summary>
        /// The raw pipe-delimited configurator message (<c>create|shaft|S|...</c>) that produced the
        /// part. Injected back into the configurator as <c>window.PRELOAD</c> to re-edit the part.
        /// </summary>
        public string Message { get; set; }

        public DateTime CreatedUtc { get; set; }

        public DateTime UpdatedUtc { get; set; }
    }

    /// <summary>
    /// Persistent record of the parts generated by "Generar pieza", so the add-in can recognise a
    /// previously generated part (by file path) and offer to regenerate it from its stored spec.
    /// </summary>
    public interface IPartRegistry
    {
        /// <summary>Entry whose path matches (case-insensitive), or null when the part is unknown.</summary>
        PartRegistryEntry Find(string path);

        /// <summary>Inserts or replaces the entry with the same path. Persists immediately.</summary>
        void Save(PartRegistryEntry entry);
    }

    /// <summary>
    /// JSON-file registry under %APPDATA%\VeradelAddin (next to the logs). One flat array of
    /// string-field objects; JSON is hand-written/hand-parsed like <see cref="Logging.JsonLinesFileSink"/>
    /// to avoid pulling in a serializer dependency for this fixed, tiny schema. Best-effort I/O: a
    /// corrupt or unreadable file behaves as an empty registry and is rewritten on the next save.
    /// </summary>
    public sealed class JsonPartRegistry : IPartRegistry
    {
        private readonly string _file;
        private readonly object _gate = new object();

        public JsonPartRegistry(string file = null)
        {
            _file = file ?? Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                "VeradelAddin", "created-parts.json");
        }

        public PartRegistryEntry Find(string path)
        {
            if (string.IsNullOrWhiteSpace(path))
            {
                return null;
            }
            lock (_gate)
            {
                foreach (var entry in Load())
                {
                    if (string.Equals(entry.Path, path, StringComparison.OrdinalIgnoreCase))
                    {
                        return entry;
                    }
                }
            }
            return null;
        }

        public void Save(PartRegistryEntry entry)
        {
            if (entry == null || string.IsNullOrWhiteSpace(entry.Path))
            {
                return;
            }
            lock (_gate)
            {
                var entries = Load();
                entries.RemoveAll(e => string.Equals(e.Path, entry.Path, StringComparison.OrdinalIgnoreCase));
                entries.Add(entry);
                Write(entries);
            }
        }

        // ---- persistence ---------------------------------------------------------------------

        private List<PartRegistryEntry> Load()
        {
            try
            {
                if (!File.Exists(_file))
                {
                    return new List<PartRegistryEntry>();
                }
                return Parse(File.ReadAllText(_file, Encoding.UTF8));
            }
            catch
            {
                return new List<PartRegistryEntry>();
            }
        }

        private void Write(List<PartRegistryEntry> entries)
        {
            try
            {
                Directory.CreateDirectory(Path.GetDirectoryName(_file));
                var sb = new StringBuilder(256);
                sb.Append("[\n");
                for (int i = 0; i < entries.Count; i++)
                {
                    var e = entries[i];
                    sb.Append("  {");
                    AppendField(sb, "path", e.Path, true);
                    AppendField(sb, "kind", e.Kind, true);
                    AppendField(sb, "message", e.Message, true);
                    AppendField(sb, "createdUtc", e.CreatedUtc.ToString("o", CultureInfo.InvariantCulture), true);
                    AppendField(sb, "updatedUtc", e.UpdatedUtc.ToString("o", CultureInfo.InvariantCulture), false);
                    sb.Append('}').Append(i < entries.Count - 1 ? ",\n" : "\n");
                }
                sb.Append("]\n");
                File.WriteAllText(_file, sb.ToString(), Encoding.UTF8);
            }
            catch
            {
                // best-effort: losing the registry must never break part generation
            }
        }

        private static void AppendField(StringBuilder sb, string name, string value, bool trailingComma)
        {
            sb.Append('"').Append(name).Append("\":");
            if (value == null)
            {
                sb.Append("null");
            }
            else
            {
                sb.Append('"').Append(Escape(value)).Append('"');
            }
            if (trailingComma)
            {
                sb.Append(',');
            }
        }

        private static string Escape(string s)
        {
            var sb = new StringBuilder(s.Length + 8);
            foreach (var c in s)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\b': sb.Append("\\b"); break;
                    case '\f': sb.Append("\\f"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < 0x20)
                        {
                            sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            sb.Append(c);
                        }
                        break;
                }
            }
            return sb.ToString();
        }

        // Minimal parser for the exact shape this class writes: an array of flat objects whose
        // values are strings (or null). Tolerant of whitespace; anything malformed aborts cleanly.
        private static List<PartRegistryEntry> Parse(string json)
        {
            var entries = new List<PartRegistryEntry>();
            int i = 0;
            SkipWs(json, ref i);
            if (i >= json.Length || json[i] != '[') return entries;
            i++;
            while (true)
            {
                SkipWs(json, ref i);
                if (i >= json.Length) return entries;
                if (json[i] == ']') return entries;
                if (json[i] != '{') return entries;
                i++;
                var fields = new Dictionary<string, string>(StringComparer.Ordinal);
                while (true)
                {
                    SkipWs(json, ref i);
                    if (i >= json.Length) return entries;
                    if (json[i] == '}') { i++; break; }
                    string name = ReadString(json, ref i);
                    if (name == null) return entries;
                    SkipWs(json, ref i);
                    if (i >= json.Length || json[i] != ':') return entries;
                    i++;
                    SkipWs(json, ref i);
                    if (i < json.Length && json[i] == 'n' && i + 4 <= json.Length && json.Substring(i, 4) == "null")
                    {
                        fields[name] = null;
                        i += 4;
                    }
                    else
                    {
                        string value = ReadString(json, ref i);
                        if (value == null) return entries;
                        fields[name] = value;
                    }
                    SkipWs(json, ref i);
                    if (i < json.Length && json[i] == ',') i++;
                }
                entries.Add(ToEntry(fields));
                SkipWs(json, ref i);
                if (i < json.Length && json[i] == ',') i++;
            }
        }

        private static PartRegistryEntry ToEntry(Dictionary<string, string> fields)
        {
            var entry = new PartRegistryEntry();
            string v;
            if (fields.TryGetValue("path", out v)) entry.Path = v;
            if (fields.TryGetValue("kind", out v)) entry.Kind = v;
            if (fields.TryGetValue("message", out v)) entry.Message = v;
            DateTime dt;
            if (fields.TryGetValue("createdUtc", out v) && v != null &&
                DateTime.TryParse(v, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out dt))
            {
                entry.CreatedUtc = dt;
            }
            if (fields.TryGetValue("updatedUtc", out v) && v != null &&
                DateTime.TryParse(v, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out dt))
            {
                entry.UpdatedUtc = dt;
            }
            return entry;
        }

        private static void SkipWs(string s, ref int i)
        {
            while (i < s.Length && (s[i] == ' ' || s[i] == '\t' || s[i] == '\r' || s[i] == '\n')) i++;
        }

        // Reads a JSON string starting at s[i] == '"'; returns its unescaped value or null on error.
        private static string ReadString(string s, ref int i)
        {
            if (i >= s.Length || s[i] != '"') return null;
            i++;
            var sb = new StringBuilder();
            while (i < s.Length)
            {
                char c = s[i];
                if (c == '"') { i++; return sb.ToString(); }
                if (c == '\\')
                {
                    i++;
                    if (i >= s.Length) return null;
                    char e = s[i];
                    switch (e)
                    {
                        case '"': sb.Append('"'); break;
                        case '\\': sb.Append('\\'); break;
                        case '/': sb.Append('/'); break;
                        case 'b': sb.Append('\b'); break;
                        case 'f': sb.Append('\f'); break;
                        case 'n': sb.Append('\n'); break;
                        case 'r': sb.Append('\r'); break;
                        case 't': sb.Append('\t'); break;
                        case 'u':
                            if (i + 4 >= s.Length) return null;
                            int code;
                            if (!int.TryParse(s.Substring(i + 1, 4), NumberStyles.HexNumber, CultureInfo.InvariantCulture, out code)) return null;
                            sb.Append((char)code);
                            i += 4;
                            break;
                        default: return null;
                    }
                    i++;
                }
                else
                {
                    sb.Append(c);
                    i++;
                }
            }
            return null;
        }
    }
}
