using System;
using System.Collections.Generic;
using VeradeAddin.Logging;
using VeradeAddin.Models;
using VeradeAddin.Services;

namespace VeradeAddin.Commands
{
    /// <summary>
    /// "Configurar pieza": part-tab entry point to the parametric part generator. Two ways in:
    /// <list type="bullet">
    /// <item>an EMPTY part (no bodies/sketches): opens the catalog and builds the chosen part from
    /// scratch. Both catalog kinds (eje and bulón — a fixed 2-level shaft) are built by the shaft
    /// engine. After a successful build, if the document is saved on disk the part is recorded in
    /// the <see cref="IPartRegistry"/> (path + raw wizard message) so it can be re-edited later.</item>
    /// <item>a part PREVIOUSLY GENERATED by this command (its path is in the registry): after an
    /// explicit warning — everything created afterwards or modified will be DELETED — the wizard
    /// reopens preloaded with the stored values, the feature tree is cleared and the part is
    /// regenerated from the new spec.</item>
    /// </list>
    /// Pure dispatch + logging; geometry goes through <see cref="ISolidWorksService"/>, UI through
    /// <see cref="IDialogService"/>, persistence through <see cref="IPartRegistry"/>.
    /// </summary>
    public sealed class ConfigurarPiezaCommand : ICommand
    {
        private readonly ISolidWorksService _sw;
        private readonly IDialogService _dialog;
        private readonly IPartRegistry _registry;
        private readonly ILogger _log;

        public ConfigurarPiezaCommand(ISolidWorksService sw, IDialogService dialog, IPartRegistry registry, ILogger log)
        {
            _sw = sw;
            _dialog = dialog;
            _registry = registry;
            _log = log;
        }

        public string Name { get { return "Generar pieza"; } }
        public string Tooltip { get { return "Generar pieza personalizada"; } }
        public string Hint { get { return "Abre el catálogo de piezas generables y crea la elegida en la pieza vacía actual (o regenera una pieza creada antes con el programa)"; } }
        public CommandIcon Icon { get { return CommandIcon.Configure; } }

        public IReadOnlyList<DocumentKind> DocumentTypes
        {
            get { return new[] { DocumentKind.Part }; }
        }

        public bool CanExecute()
        {
            return _sw.IsActivePartEmpty() || FindRegisteredEntry() != null;
        }

        public void Execute()
        {
            const string docType = "Part";

            bool isEmpty = _sw.IsActivePartEmpty();
            var registered = FindRegisteredEntry();

            if (!isEmpty && registered == null)
            {
                _log.Log(Name, docType, LogOutcome.Cancel, "Active part is not empty (or no part active)");
                _dialog.ShowMessage(Name,
                    "Este comando genera la pieza desde cero en un documento de pieza vacío.\n\n" +
                    "Abra una pieza nueva (sin operaciones en el árbol) e inténtelo de nuevo.");
                return;
            }

            // Re-edit of a part this program generated: warn (destructive) before opening the wizard.
            bool isReEdit = !isEmpty && registered != null;
            if (isReEdit)
            {
                bool proceed = _dialog.Confirm(Name,
                    "Esta pieza ya se creó con el programa.\n\n" +
                    "Si continúa, se abrirá el asistente con los valores guardados y, al confirmar, " +
                    "la pieza se regenerará desde cero:\n\n" +
                    "TODO LO CREADO DESPUÉS O MODIFICADO SE ELIMINARÁ.\n\n" +
                    "¿Desea continuar?");
                if (!proceed)
                {
                    _log.Log(Name, docType, LogOutcome.Cancel, "User declined the regenerate warning");
                    return;
                }
            }

            var selection = _dialog.ShowPartConfigurator(isReEdit ? registered.Message : null);
            if (selection == null || selection.Shaft == null)
            {
                _log.Log(Name, docType, LogOutcome.Cancel, "User cancelled the configurator");
                return;
            }

            if (isReEdit)
            {
                string clearError = _sw.ClearActivePart();
                if (clearError != null)
                {
                    _log.Log(Name, docType, LogOutcome.Error, "Could not clear the part before regenerating", clearError);
                    _dialog.ShowMessage(Name, "No se pudo vaciar la pieza para regenerarla:\n" + clearError);
                    return;
                }
            }

            BuildShaft(selection, docType);
        }

        /// <summary>Registry entry for the active document, or null (no doc / unsaved / unknown path).</summary>
        private PartRegistryEntry FindRegisteredEntry()
        {
            var doc = _sw.GetActiveDocument();
            if (doc == null || doc.Kind != DocumentKind.Part || !doc.HasPath)
            {
                return null;
            }
            return _registry.Find(doc.FilePath);
        }

        private void BuildShaft(PartConfiguratorSelection selection, string docType)
        {
            var spec = selection.Shaft;
            string partLabel = selection.Part == ConfigurablePart.Bolt ? "Bulón" : "Eje";

            var result = _sw.CreateShaft(spec);
            if (result.Success)
            {
                _log.Log(Name, docType, LogOutcome.Success,
                    partLabel + " created (" + result.LevelCount + " levels, total " + result.TotalLengthMm +
                    " mm, " + result.SplitLineCount + " split lines, " + result.KeywayCount + " keyways, " +
                    result.GrooveCount + " grooves, " + result.UndercutCount + " undercuts, " +
                    result.CenterHoleCount + " centre points, " + result.ThreadCount + " cosmetic threads, " +
                    result.FilletCount + " fillets, " + result.ChamferCount + " chamfers)" +
                    (result.Warning != null ? " — skipped: " + result.Warning.Replace("\n", " | ") : ""));

                RegisterIfSaved(selection);

                _dialog.ShowMessage(Name,
                    partLabel + " creado.\n" +
                    "Niveles: " + result.LevelCount + "\n" +
                    (result.SplitLineCount > 0 ? "Líneas de división: " + result.SplitLineCount + "\n" : "") +
                    (result.KeywayCount > 0 ? "Chavetas: " + result.KeywayCount + "\n" : "") +
                    (result.GrooveCount > 0 ? "Ranuras: " + result.GrooveCount + "\n" : "") +
                    (result.UndercutCount > 0 ? "Entalladuras: " + result.UndercutCount + "\n" : "") +
                    (result.CenterHoleCount > 0 ? "Puntos de centrado: " + result.CenterHoleCount + "\n" : "") +
                    (result.ThreadCount > 0 ? "Roscas cosméticas: " + result.ThreadCount + "\n" : "") +
                    (result.FilletCount > 0 ? "Redondeos: " + result.FilletCount + "\n" : "") +
                    (result.ChamferCount > 0 ? "Chaflanes: " + result.ChamferCount + "\n" : "") +
                    "Longitud total: " + result.TotalLengthMm + " mm" +
                    (result.Warning != null
                        ? "\n\nATENCIÓN — operaciones omitidas por error:\n" + result.Warning
                        : ""));
            }
            else
            {
                _log.Log(Name, docType, LogOutcome.Error, partLabel + " creation failed", result.Error);
                _dialog.ShowMessage(Name, "No se pudo crear " + (selection.Part == ConfigurablePart.Bolt ? "el bulón" : "el eje") + ":\n" + result.Error);
            }
        }

        // Records (or refreshes) the generated part in the registry, keyed by its saved path. A
        // never-saved document has no path yet, so it simply is not recorded (chosen behaviour).
        private void RegisterIfSaved(PartConfiguratorSelection selection)
        {
            try
            {
                var doc = _sw.GetActiveDocument();
                if (doc == null || !doc.HasPath || string.IsNullOrEmpty(selection.RawMessage))
                {
                    return;
                }
                var existing = _registry.Find(doc.FilePath);
                _registry.Save(new PartRegistryEntry
                {
                    Path = doc.FilePath,
                    Kind = selection.Part == ConfigurablePart.Bolt ? "bolt" : "shaft",
                    Message = selection.RawMessage,
                    CreatedUtc = existing != null ? existing.CreatedUtc : DateTime.UtcNow,
                    UpdatedUtc = DateTime.UtcNow
                });
            }
            catch (Exception ex)
            {
                // best-effort: the part is already built; a registry failure must not surface as an error
                _log.Log(Name, "Part", LogOutcome.Error, "Part registry save failed", ex.ToString());
            }
        }
    }
}
